name: Generate Badge Images

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Check out repository under $GITHUB_WORKSPACE, so the job can access it
    - uses: actions/checkout@v3

    # Run using Python 3.8 for consistency and aiohttp
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
        architecture: 'x64'
        
    # Install dependencies with `pip`
    #- name: Install requirements
    #  run: |
    #    python3 -m pip install --upgrade pip setuptools wheel

    # Generate all statistics images
    - name: Generate images
      run: |
        #python3 --version
        python3 generate_badge.py
      #env:
      #  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Commit all changed files to the repository
    - name: Commit to the repo
      run: |
        git config --global user.name "kuldeepsingh-in"
        git config --global user.email "github-stats[bot]@kuldeepsingh-in.github.io"
        git add .
        # Force the build to succeed, even if no files were changed
        git commit -m 'Update generated files' || true
        git push
